CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user'
);

CREATE UNIQUE INDEX users_email_uq_idx ON users (email);

CREATE TABLE quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_no TEXT NOT NULL,
    client_name TEXT NOT NULL,
    attn_name TEXT NOT NULL DEFAULT '',
    attn_position TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    project TEXT NOT NULL,
    discount_type TEXT NOT NULL DEFAULT '',
    discount_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX quotations_quotation_no_uq_idx ON quotations (quotation_no);
CREATE INDEX quotations_created_at_idx ON quotations (created_at DESC);

CREATE TABLE quotation_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id BIGINT NOT NULL REFERENCES quotations (id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX quotation_sections_quotation_id_position_idx
    ON quotation_sections (quotation_id, position);

CREATE TABLE quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES quotation_sections (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit TEXT NOT NULL DEFAULT '',
    price DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE INDEX quotation_items_section_id_idx ON quotation_items (section_id);

CREATE TABLE quotation_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES quotation_sections (id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX quotation_details_section_id_position_idx
    ON quotation_details (section_id, position);

CREATE OR REPLACE FUNCTION generate_quotation_no()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    current_year TEXT := TO_CHAR(CURRENT_DATE, 'YYYY');
    next_number INTEGER;
BEGIN
    SELECT
        COALESCE(
            MAX(
                (
                    regexp_match(
                        quotation_no,
                        '^Q-' || current_year || '-([0-9]{4})$'
                    )
                )[1]::INTEGER
            ),
            0
        ) + 1
    INTO next_number
    FROM quotations
    WHERE quotation_no LIKE 'Q-' || current_year || '-%';

    RETURN 'Q-' || current_year || '-' || LPAD(next_number::TEXT, 4, '0');
END;
$$;
