CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket TEXT NOT NULL, -- Example: widia-assets
    object_name TEXT NOT NULL, -- Example: quotations/2026/06/uuid-file.pdf
    original_filename TEXT NOT NULL, -- Example: quotation-client-a.pdf
    stored_filename TEXT NOT NULL, -- Example: uuid-file.pdf
    mime_type TEXT NOT NULL DEFAULT 'application/octet-stream', -- Example: application/pdf
    extension TEXT NOT NULL DEFAULT '', -- Example: pdf
    size BIGINT NOT NULL DEFAULT 0, -- Example: 245760 (bytes)
    etag TEXT NOT NULL DEFAULT '', -- Example: 9b2cf535f27731c974343645a3985328
    is_private BOOLEAN NOT NULL DEFAULT TRUE, -- Example: TRUE for private object
    uploaded_by BIGINT REFERENCES users (id) ON DELETE SET NULL, -- Example: 1
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS assets_bucket_object_name_uq_idx
    ON assets (bucket, object_name);

CREATE INDEX IF NOT EXISTS assets_uploaded_by_idx ON assets (uploaded_by);
CREATE INDEX IF NOT EXISTS assets_created_at_idx ON assets (created_at DESC);
