CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),

    bucket TEXT NOT NULL,
    object_name TEXT NOT NULL,
    -- Nama objek di storage, DAN satu-satunya penentu kelompoknya: segmen
    -- sebelum nama berkas adalah foldernya — images/brand, documents/quotation.
    -- Tidak ada kolom kelompok tersendiri; lihat catatan pada indeks awalan di
    -- bawah, dan usecase.AssetGroup yang membacanya balik.

    key TEXT,
    -- Nama slot yang dapat diganti isinya, mis. 'logo-widia-kencana'. NULL untuk
    -- aset biasa, dan HARUS null — bukan string kosong — karena indeks uniknya
    -- akan menganggap dua string kosong bertabrakan.
    --
    -- Gunanya menemukan aset TANPA tahu tokennya. Mengganti isi slot tidak
    -- mengubah token, sehingga seluruh dokumen yang menunjuk token itu ikut
    -- berubah tanpa disunting satu per satu.

    original_filename TEXT NOT NULL,
    stored_filename TEXT NOT NULL,
    mime_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    extension TEXT NOT NULL DEFAULT '',

    size BIGINT NOT NULL DEFAULT 0,
    etag TEXT NOT NULL DEFAULT '',
    checksum_sha256 TEXT,

    status TEXT NOT NULL DEFAULT 'pending',
    upload_method TEXT NOT NULL DEFAULT 'presigned_put',

    multipart_upload_id TEXT,
    multipart_part_size BIGINT,
    multipart_total_parts INTEGER,

    is_private BOOLEAN NOT NULL DEFAULT TRUE,

    uploaded_by BIGINT
        REFERENCES users (id)
        ON DELETE SET NULL,

    presigned_expires_at TIMESTAMPTZ,
    uploaded_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    failure_code TEXT,
    failure_message TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT assets_bucket_not_empty_chk
        CHECK (BTRIM(bucket) <> ''),

    CONSTRAINT assets_key_not_empty_chk
        CHECK (key IS NULL OR BTRIM(key) <> ''),

    CONSTRAINT assets_object_name_not_empty_chk
        CHECK (BTRIM(object_name) <> ''),

    CONSTRAINT assets_original_filename_not_empty_chk
        CHECK (BTRIM(original_filename) <> ''),

    CONSTRAINT assets_stored_filename_not_empty_chk
        CHECK (BTRIM(stored_filename) <> ''),

    CONSTRAINT assets_size_non_negative_chk
        CHECK (size >= 0),

    CONSTRAINT assets_multipart_part_size_chk
        CHECK (
            multipart_part_size IS NULL
            OR multipart_part_size > 0
        ),

    CONSTRAINT assets_multipart_total_parts_chk
        CHECK (
            multipart_total_parts IS NULL
            OR multipart_total_parts > 0
        ),

    CONSTRAINT assets_status_chk
        CHECK (
            status IN (
                'pending',
                'uploading',
                'uploaded',
                'failed',
                'deleted'
            )
        ),

    CONSTRAINT assets_upload_method_chk
        CHECK (
            upload_method IN (
                'direct',
                'presigned_put',
                'presigned_post',
                'multipart'
            )
        ),

    CONSTRAINT assets_multipart_fields_chk
        CHECK (
            upload_method = 'multipart'
            OR (
                multipart_upload_id IS NULL
                AND multipart_part_size IS NULL
                AND multipart_total_parts IS NULL
            )
        ),

    CONSTRAINT assets_uploaded_state_chk
        CHECK (
            status <> 'uploaded'
            OR uploaded_at IS NOT NULL
        ),

    CONSTRAINT assets_failed_state_chk
        CHECK (
            status <> 'failed'
            OR failed_at IS NOT NULL
        ),

    CONSTRAINT assets_deleted_state_chk
        CHECK (
            status <> 'deleted'
            OR deleted_at IS NOT NULL
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS assets_bucket_object_name_uq_idx
    ON assets (bucket, object_name)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS assets_token_uq_idx
    ON assets (token);

CREATE INDEX IF NOT EXISTS assets_uploaded_by_idx
    ON assets (uploaded_by)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS assets_created_at_idx
    ON assets (created_at DESC);

CREATE INDEX IF NOT EXISTS assets_status_idx
    ON assets (status);

-- text_pattern_ops, dan itu bukan hiasan: tanpanya, penyaringan kelompok
-- (object_name LIKE 'images/brand/%') tidak dapat memakai indeks sama sekali dan
-- jatuh ke pemindaian penuh. Dengan opclass ini ia menjadi range scan.
CREATE INDEX IF NOT EXISTS assets_object_name_prefix_idx
    ON assets (object_name text_pattern_ops);

-- Hanya untuk yang hidup, sehingga key milik aset yang sudah dihapus boleh
-- dipakai ulang. Unik GLOBAL, bukan per kelompok: nama seperti
-- 'logo-widia-kencana' tidak masuk akal muncul dua kali di tempat berbeda.
CREATE UNIQUE INDEX IF NOT EXISTS assets_key_uq_idx
    ON assets (key)
    WHERE key IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS assets_mime_type_idx
    ON assets (mime_type);

CREATE INDEX IF NOT EXISTS assets_extension_idx
    ON assets (extension);

CREATE INDEX IF NOT EXISTS assets_uploaded_by_created_at_idx
    ON assets (uploaded_by, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS assets_pending_expiry_idx
    ON assets (presigned_expires_at)
    WHERE status IN ('pending', 'uploading')
      AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS assets_multipart_upload_id_idx
    ON assets (multipart_upload_id)
    WHERE multipart_upload_id IS NOT NULL;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS assets_set_updated_at_trg ON assets;

CREATE TRIGGER assets_set_updated_at_trg
BEFORE UPDATE ON assets
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Frontend
--    │
--    ├── minta presigned URL ──> Golang API
--    │                            ├── authorization
--    │                            ├── insert assets: pending
--    │                            └── generate presigned PUT
--    │
--    ├── upload langsung ──────> MinIO
--    │
--    └── complete upload ──────> Golang API
--                                 ├── StatObject MinIO
--                                 ├── validasi size/type
--                                 └── assets: uploaded
