CREATE TABLE IF NOT EXISTS document_papers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,
    -- Example: A4, Letter, F4, Continuous Form

    media_type TEXT NOT NULL DEFAULT 'sheet',
    -- Values: sheet, continuous

    width NUMERIC(10,3) NOT NULL,
    -- Base portrait width

    height NUMERIC(10,3) NOT NULL,
    -- Base portrait height / perforation length

    unit TEXT NOT NULL DEFAULT 'mm',
    -- Values: mm, in, cm, pt, px, m

    allow_portrait BOOLEAN NOT NULL DEFAULT TRUE,
    allow_landscape BOOLEAN NOT NULL DEFAULT TRUE,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_papers_media_type_chk
        CHECK (media_type IN ('sheet', 'continuous')),

    CONSTRAINT document_papers_unit_chk
        CHECK (unit IN ('mm', 'in', 'cm', 'pt', 'px', 'm')),

    CONSTRAINT document_papers_status_chk
        CHECK (status IN ('active', 'inactive')),

    CONSTRAINT document_papers_width_positive_chk
        CHECK (width > 0),

    CONSTRAINT document_papers_height_positive_chk
        CHECK (height > 0),

    CONSTRAINT document_papers_orientation_allowed_chk
        CHECK (allow_portrait OR allow_landscape)
);

CREATE UNIQUE INDEX IF NOT EXISTS document_papers_name_size_uq_idx
    ON document_papers (
        name,
        media_type,
        width,
        height,
        unit
    );

CREATE INDEX IF NOT EXISTS document_papers_status_idx
    ON document_papers (status);

CREATE INDEX IF NOT EXISTS document_papers_media_type_idx
    ON document_papers (media_type);

INSERT INTO document_papers (
    name,
    media_type,
    width,
    height,
    unit,
    allow_portrait,
    allow_landscape,
    status
) VALUES
    -- Standard sheet paper
    ('A4',     'sheet', 210, 297, 'mm', TRUE, TRUE, 'active'),
    ('Letter', 'sheet', 8.5, 11,  'in', TRUE, TRUE, 'active'),
    ('F4',     'sheet', 210, 330, 'mm', TRUE, TRUE, 'active'),

    -- =========================================================
    -- CONTINUOUS FORM
    -- Height merupakan panjang satu halaman/perforation
    -- =========================================================
    ('Continuous Form', 'continuous', 9.5,    5.5, 'in', TRUE, TRUE, 'active'),
    ('Continuous Form', 'continuous', 9.5,    11,  'in', TRUE, TRUE, 'active'),
    ('Continuous Form', 'continuous', 9.5,    12,  'in', TRUE, TRUE, 'active'),
    ('Continuous Form', 'continuous', 10,     11,  'in', TRUE, TRUE, 'active'),
    ('Continuous Form', 'continuous', 10,     12,  'in', TRUE, TRUE, 'active'),
    ('Continuous Form', 'continuous', 14.875, 11,  'in', TRUE, TRUE, 'active'),

    -- =========================================================
    -- THERMAL PAPER
    -- Width adalah lebar roll.
    -- Height adalah tinggi awal/default canvas dan dapat bertambah
    -- mengikuti panjang konten saat preview atau export.
    -- =========================================================
    ('Thermal Paper', 'thermal', 58,  100, 'mm', TRUE, FALSE, 'active'),
    ('Thermal Paper', 'thermal', 80,  100, 'mm', TRUE, FALSE, 'active'),
    ('Thermal Paper', 'thermal', 110, 100, 'mm', TRUE, FALSE, 'active')

ON CONFLICT (
    name,
    media_type,
    width,
    height,
    unit
) DO NOTHING;
