CREATE TABLE IF NOT EXISTS document_property_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    document_property_id BIGINT NOT NULL REFERENCES document_properties (id) ON DELETE CASCADE,

    value TEXT NOT NULL,
    -- Example: left, center, right, top, Arial

    label TEXT NOT NULL,
    -- Example: Left, Center, Right, Top, Arial

    position INTEGER NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_property_options_status_chk
        CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_property_options_property_value_uq_idx
    ON document_property_options (document_property_id, value);

CREATE INDEX IF NOT EXISTS document_property_options_property_position_idx
    ON document_property_options (document_property_id, position);

CREATE INDEX IF NOT EXISTS document_property_options_status_idx
    ON document_property_options (status);

INSERT INTO document_property_options (
    document_property_id,
    value,
    label,
    position,
    status
) 
SELECT
    document_properties.id,
    seed_options.value,
    seed_options.label,
    seed_options.position,
    seed_options.status
FROM (
    VALUES
        -- Text align
        ('text-align', 'left', 'Left', 1, 'active'),
        ('text-align', 'center', 'Center', 2, 'active'),
        ('text-align', 'right', 'Right', 3, 'active'),
        ('text-align', 'justify', 'Justify', 4, 'active'),

        -- Vertical align
        ('vertical-align', 'top', 'Top', 1, 'active'),
        ('vertical-align', 'middle', 'Middle', 2, 'active'),
        ('vertical-align', 'bottom', 'Bottom', 3, 'active'),

        -- Font family
        ('font-family', 'Arial', 'Arial', 1, 'active'),
        ('font-family', 'Times New Roman', 'Times New Roman', 2, 'active'),
        ('font-family', 'Calibri', 'Calibri', 3, 'active'),

        -- Font weight
        ('font-weight', '300', 'Light', 1, 'active'),
        ('font-weight', '400', 'Regular', 2, 'active'),
        ('font-weight', '500', 'Medium', 3, 'active'),
        ('font-weight', '600', 'Semi Bold', 4, 'active'),
        ('font-weight', '700', 'Bold', 5, 'active'),

        -- Display
        ('display', 'block', 'Block', 1, 'active'),
        ('display', 'flex', 'Flex', 2, 'active'),
        ('display', 'grid', 'Grid', 3, 'active'),
        ('display', 'inline-block', 'Inline Block', 4, 'active'),
        ('display', 'none', 'None', 5, 'active'),

        -- Flex direction
        ('flex-direction', 'row', 'Row', 1, 'active'),
        ('flex-direction', 'column', 'Column', 2, 'active'),
        ('flex-direction', 'row-reverse', 'Row Reverse', 3, 'active'),
        ('flex-direction', 'column-reverse', 'Column Reverse', 4, 'active'),

        -- Justify content
        ('justify-content', 'flex-start', 'Flex Start', 1, 'active'),
        ('justify-content', 'center', 'Center', 2, 'active'),
        ('justify-content', 'flex-end', 'Flex End', 3, 'active'),
        ('justify-content', 'space-between', 'Space Between', 4, 'active'),
        ('justify-content', 'space-around', 'Space Around', 5, 'active'),
        ('justify-content', 'space-evenly', 'Space Evenly', 6, 'active'),

        -- Align items
        ('align-items', 'stretch', 'Stretch', 1, 'active'),
        ('align-items', 'flex-start', 'Flex Start', 2, 'active'),
        ('align-items', 'center', 'Center', 3, 'active'),
        ('align-items', 'flex-end', 'Flex End', 4, 'active'),
        ('align-items', 'baseline', 'Baseline', 5, 'active'),

        -- List style type
        ('list-style-type', 'disc', 'Bulleted', 1, 'active'),
        ('list-style-type', 'decimal', 'Numbered', 2, 'active'),
        ('list-style-type', 'lower-alpha', 'Alphabet', 3, 'active'),
        ('list-style-type', 'none', 'None', 4, 'active'),

        -- Color palette
        ('color', '#2563EB', 'Primary', 1, 'active'),
        ('color', '#64748B', 'Secondary', 2, 'active'),
        ('color', '#7C3AED', 'Accent', 3, 'active'),
        ('background-color', '#2563EB', 'Primary', 1, 'active'),
        ('background-color', '#64748B', 'Secondary', 2, 'active'),
        ('background-color', '#7C3AED', 'Accent', 3, 'active'),

        -- Grid template columns
        ('grid-template-columns', '[100]', 'Single', 1, 'active'),
        ('grid-template-columns', '[50,50]', 'Half', 2, 'active'),
        ('grid-template-columns', '[30,70]', 'Left', 3, 'active'),
        ('grid-template-columns', '[70,30]', 'Right', 4, 'active'),
        ('grid-template-columns', '[33,33,34]', 'Thirds', 5, 'active')
) AS seed_options (
    property_code,
    value,
    label,
    position,
    status
)
JOIN document_properties
    ON document_properties.code = seed_options.property_code
ON CONFLICT (document_property_id, value) DO NOTHING;
