CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS document_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Public identifier for frontend communication

    code TEXT NOT NULL,
    -- Example: grid, text, image, watermark, table

    name TEXT NOT NULL,
    -- Example: Grid, Text, Image, Watermark

    renderer_type TEXT NOT NULL DEFAULT 'html',
    -- Values: html

    renderer_tag TEXT NOT NULL,
    -- Example: div, p, img, table, hr

    content_type TEXT NOT NULL DEFAULT 'none',
    -- Values: none, text, image, table

    is_container BOOLEAN NOT NULL DEFAULT FALSE,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_elements_renderer_type_chk
        CHECK (renderer_type IN ('html')),

    CONSTRAINT document_elements_content_type_chk
        CHECK (content_type IN ('none', 'text', 'image', 'table')),

    CONSTRAINT document_elements_status_chk
        CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_elements_code_uq_idx
    ON document_elements (code);

CREATE UNIQUE INDEX IF NOT EXISTS document_elements_token_uq_idx
    ON document_elements (token);

CREATE INDEX IF NOT EXISTS document_elements_status_idx
    ON document_elements (status);

INSERT INTO document_elements (
    code,
    name,
    renderer_type,
    renderer_tag,
    content_type,
    is_container,
    status
) VALUES
    ('grid', 'Grid', 'html', 'div', 'none', TRUE, 'active'),
    ('text', 'Text', 'html', 'p', 'text', FALSE, 'active'),
    ('image', 'Image', 'html', 'img', 'image', FALSE, 'active'),
    ('watermark', 'Watermark', 'html', 'div', 'image', FALSE, 'active'),
    ('table', 'Table', 'html', 'table', 'table', FALSE, 'active'),
    ('divider', 'Divider', 'html', 'hr', 'none', FALSE, 'active'),
    ('spacer', 'Spacer', 'html', 'div', 'none', FALSE, 'active')
ON CONFLICT (code) DO NOTHING;
