CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS document_layers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Public identifier for frontend communication

    document_id BIGINT NOT NULL REFERENCES documents (id) ON DELETE CASCADE,

    parent_id BIGINT REFERENCES document_layers (id) ON DELETE CASCADE,
    -- Nullable for root layer inside a region

    document_element_id BIGINT NOT NULL REFERENCES document_elements (id),

    region TEXT NOT NULL DEFAULT 'body',
    -- Values: header, body, footer

    name TEXT NOT NULL,
    -- Example: Header Grid, Company Logo, Payment Table

    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Element content payload. Example: {"text":"Payment Details"}

    properties JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Resolved editable properties. Example: {"font-size":"16px"}

    position INTEGER NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, deleted

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_layers_region_chk
        CHECK (region IN ('header', 'body', 'footer')),

    CONSTRAINT document_layers_status_chk
        CHECK (status IN ('active', 'deleted'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_layers_token_uq_idx
    ON document_layers (token);

CREATE INDEX IF NOT EXISTS document_layers_document_region_position_idx
    ON document_layers (document_id, region, position);

CREATE INDEX IF NOT EXISTS document_layers_parent_position_idx
    ON document_layers (parent_id, position);

CREATE INDEX IF NOT EXISTS document_layers_document_element_id_idx
    ON document_layers (document_element_id);

CREATE INDEX IF NOT EXISTS document_layers_status_idx
    ON document_layers (status);
