CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Public identifier for frontend communication

    document_paper_id BIGINT NOT NULL REFERENCES document_papers (id),

    parent_id BIGINT REFERENCES documents (id) ON DELETE SET NULL,
    -- Nullable for original document. Used for cloned/versioned document lineage

    name TEXT NOT NULL,
    -- Example: Quotation Default, Invoice Default

    document_type TEXT NOT NULL DEFAULT 'custom',
    -- Kosakata TERTUTUP, ditegakkan di usecase — bukan di sini:
    --   quotation, purchase-order, bast, delivery-note, service-report,
    --   invoice, cv
    --
    -- Sengaja tanpa CHECK. Daftarnya bertambah seiring jenis dokumen baru, dan
    -- constraint di database menuntut ALTER TABLE pada setiap penambahan —
    -- langkah manual yang akan terlewat, lalu muncul sebagai penolakan yang
    -- tidak disebut kode mana pun. Lihat allowedDocumentTypes di
    -- internal/usecase/document_usecase.go.
    --
    -- DEFAULT 'custom' di bawah adalah PENINGGALAN dan tidak lagi berlaku:
    -- jenis kini wajib disebut, dan 'custom' akan ditolak. Dibiarkan supaya
    -- baris lama tidak berubah artinya; jangan diandalkan.

    status TEXT NOT NULL DEFAULT 'draft',
    -- Values: draft, active, inactive, archived
    -- Menghapus dokumen MENGHAPUS barisnya; tidak ada status 'deleted'.

    variables JSONB NOT NULL DEFAULT '{}',
    -- Kantong nilai turunan lain yang ingin ditanyakan kembali: dp_percentage,
    -- ppn_rate, nomor kendaraan pada surat jalan, jam teknisi pada service
    -- report. Bentuknya objek datar — lihat penjaganya di usecase.
    --
    -- JSONB, BUKAN tabel key-value. Di database yang punya JSONB, tabel EAV
    -- menukar satu kolom dengan sebuah tabel, sebuah join per variabel, dan
    -- pengecoran tipe di setiap kueri laporan — sementara keluwesannya sama
    -- persis. Yang hilang pada keduanya juga sama: tipe tidak ditegakkan dan
    -- kunci tidak punya kosakata.
    --
    -- grand_total TINGGAL DI SINI juga, bukan sebagai kolom tersendiri. Yang
    -- ditukar dengan itu penegakan tipe oleh database — tetapi tidak seluruhnya:
    -- INDEKS EKSPRESI di bawah menghitung nilainya ketika barisnya DITULIS,
    -- sehingga "Rp 184.405.410" ditolak saat INSERT. Selama indeks itu terpasang,
    -- baris bertipe salah tidak pernah masuk.
    --
    -- Penjaga di usecase tetap wajib, dan bukan pengulangan: galat dari indeks
    -- adalah galat Postgres mentah yang sampai ke klien sebagai 500 menyebut nama
    -- indeks, sedangkan numericVariableKeys menjawabnya 400 dengan kalimat yang
    -- menyebut kuncinya. NEGATIF pun hanya dijaga di sana — bagi database ia
    -- angka yang sah.

    content JSONB NOT NULL DEFAULT '{"pages": []}',
    -- Isi kanvas: halaman beserta elemennya.
    -- Dikelola realtime lewat ws /document-design/:token, bukan lewat REST.

    content_version BIGINT NOT NULL DEFAULT 0,
    -- Nomor revisi isi kanvas. Dipakai sebagai compare-and-set saat menyimpan,
    -- sehingga penulisan dari dua proses tidak saling menimpa diam-diam.

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT documents_status_chk
        CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE UNIQUE INDEX IF NOT EXISTS documents_token_uq_idx
    ON documents (token);

CREATE INDEX IF NOT EXISTS documents_document_paper_id_idx
    ON documents (document_paper_id);

CREATE INDEX IF NOT EXISTS documents_parent_id_idx
    ON documents (parent_id);

CREATE INDEX IF NOT EXISTS documents_document_type_idx
    ON documents (document_type);

-- Indeks EKSPRESI atas grand_total di dalam kantong.
--
-- Tanpa ini, setiap laporan yang menjumlahkan nilai dokumen memindai seluruh
-- tabel dan mengecor tiap barisnya. Dengan kolom biasa indeks ini datang
-- sendirinya; dengan kantong, ia harus disebut.
CREATE INDEX IF NOT EXISTS documents_grand_total_idx
    ON documents (((variables->>'grand_total')::numeric));

-- Indeks UNIK atas nomor dokumen di dalam kantong.
--
-- document_no dilahirkan server saat create (WK/<KODE>/<YYMMDD><URUT>) dan
-- tidak boleh ada dua dokumen memakai nomor yang sama, apa pun yang keliru di
-- lapisan atas — pencacahnya di document_number_counters, dan indeks ini jaring
-- terakhirnya. Parsial, supaya dokumen lama yang lahir sebelum fitur ini tidak
-- terganggu.
CREATE UNIQUE INDEX IF NOT EXISTS documents_document_no_uq_idx
    ON documents ((variables->>'document_no'))
    WHERE variables ? 'document_no';

CREATE INDEX IF NOT EXISTS documents_status_idx
    ON documents (status);

CREATE INDEX IF NOT EXISTS documents_created_at_idx
    ON documents (created_at DESC);

-- Pencacah nomor dokumen: satu baris per jenis per hari.
--
-- Nomor dokumen berbentuk WK/<KODE>/<YYMMDD><URUT>, dan URUT diambil dari sini
-- lewat satu UPSERT yang mengembalikan nilainya — atomik, sehingga dua dokumen
-- yang dibuat bersamaan tidak pernah menerima urutan yang sama. Menghitungnya
-- dari MAX() dokumen yang ada adalah lomba: dua permintaan membaca max yang
-- sama lalu sama-sama menambah satu.
--
-- CELAH URUTAN DISENGAJA DIBIARKAN. Urutan diambil SEBELUM barisnya ditulis,
-- jadi pembuatan yang gagal sesudahnya membakar satu nomor. Menutupnya berarti
-- transaksi yang memegang kunci pencacah selama INSERT dokumen berlangsung —
-- ongkos yang tidak sepadan dengan nomor yang sekadar melompat.
--
-- document_type TIDAK ber-FK ke mana pun: kosakatanya milik usecase
-- (allowedDocumentTypes), sama seperti alasan documents.document_type tanpa
-- CHECK. Kode pada nomornya sendiri (QTN, PO, BA, SJ, SR, INV, CV) hidup di
-- documentNumberCodes, internal/usecase/document_usecase.go.
--
-- Baris lama tidak pernah dibaca lagi setelah harinya lewat. Dibiarkan —
-- ukurannya tujuh baris per hari paling banyak, dan riwayat "sampai mana urutan
-- hari itu" justru keterangan yang berguna saat ada yang menanyakan nomor yang
-- melompat.
CREATE TABLE IF NOT EXISTS document_number_counters (
    document_type TEXT NOT NULL,
    day DATE NOT NULL,
    last_seq INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (document_type, day)
);
