CREATE TABLE IF NOT EXISTS document_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code TEXT NOT NULL,
    -- Example: grid, text, image, list

    name TEXT NOT NULL,
    -- Example: Grid, Text, Image, List

    renderer_type TEXT NOT NULL DEFAULT 'html',
    -- Values: html

    renderer_tag TEXT NOT NULL,
    -- Example: div, p, img, ul, table, hr

    content_type TEXT NOT NULL DEFAULT 'none',
    -- Values: none, text, image, list, table, signature, code, instruction

    is_container BOOLEAN NOT NULL DEFAULT FALSE,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_elements_renderer_type_chk
        CHECK (renderer_type IN ('html')),

    CONSTRAINT document_elements_content_type_chk
        CHECK (content_type IN ('none', 'text', 'image', 'list', 'table', 'signature', 'code', 'instruction')),

    CONSTRAINT document_elements_status_chk
        CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_elements_code_uq_idx
    ON document_elements (code);

CREATE INDEX IF NOT EXISTS document_elements_status_idx
    ON document_elements (status);

INSERT INTO document_elements (
    code,
    name,
    renderer_type,
    renderer_tag,
    content_type,
    is_container,
    status
) VALUES
    ('grid', 'Grid', 'html', 'div', 'none', TRUE, 'active'),
    ('text', 'Text', 'html', 'p', 'text', FALSE, 'active'),
    ('image', 'Image', 'html', 'img', 'image', FALSE, 'active'),
    ('list', 'List', 'html', 'ul', 'list', FALSE, 'active'),
    ('table', 'Table', 'html', 'table', 'table', FALSE, 'active'),
    ('divider', 'Divider', 'html', 'hr', 'none', FALSE, 'active'),
    ('spacer', 'Spacer', 'html', 'div', 'none', FALSE, 'active'),
    ('signature', 'Signature', 'html', 'div', 'signature', FALSE, 'active'),
    ('qr-code', 'QR Code', 'html', 'div', 'code', FALSE, 'active'),
    ('barcode', 'Barcode', 'html', 'div', 'code', FALSE, 'active'),
    ('page-break', 'Page Break', 'html', 'div', 'instruction', FALSE, 'active')
ON CONFLICT (code) DO NOTHING;
