CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS document_element_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Public identifier for frontend communication

    document_element_id BIGINT NOT NULL REFERENCES document_elements (id) ON DELETE CASCADE,
    document_property_id BIGINT NOT NULL REFERENCES document_properties (id) ON DELETE CASCADE,

    default_value TEXT NOT NULL DEFAULT '',
    -- Example: 16, 24, #FFFFFF, flex-start

    position INTEGER NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_element_properties_status_chk
        CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_element_properties_element_property_uq_idx
    ON document_element_properties (document_element_id, document_property_id);

CREATE UNIQUE INDEX IF NOT EXISTS document_element_properties_token_uq_idx
    ON document_element_properties (token);

CREATE INDEX IF NOT EXISTS document_element_properties_element_position_idx
    ON document_element_properties (document_element_id, position);

CREATE INDEX IF NOT EXISTS document_element_properties_property_idx
    ON document_element_properties (document_property_id);

CREATE INDEX IF NOT EXISTS document_element_properties_status_idx
    ON document_element_properties (status);

INSERT INTO document_element_properties (
    document_element_id,
    document_property_id,
    default_value,
    position,
    status
)
SELECT
    document_elements.id,
    document_properties.id,
    seed_mappings.default_value,
    seed_mappings.position,
    seed_mappings.status
FROM (
    VALUES
        -- Grid
        ('grid', 'display', 'grid', 1, 'active'),
        ('grid', 'grid-template-columns', '[100]', 2, 'active'),
        ('grid', 'padding', '0', 3, 'active'),
        ('grid', 'justify-items', 'stretch', 4, 'active'),
        ('grid', 'align-items', 'stretch', 5, 'active'),

        -- Text
        ('text', 'font-family', 'Arial', 1, 'active'),
        ('text', 'font-size', '16', 2, 'active'),
        ('text', 'font-weight', '400', 3, 'active'),
        ('text', 'font-style', 'normal', 4, 'active'),
        ('text', 'text-decoration', 'none', 5, 'active'),
        ('text', 'line-height', '1.5', 6, 'active'),
        ('text', 'color', '#000000', 7, 'active'),
        ('text', 'text-align', 'left', 8, 'active'),
        ('text', 'padding', '0', 9, 'active'),
        ('text', 'margin', '0', 10, 'active'),

        -- Image
        ('image', 'width', 'auto', 1, 'active'),
        ('image', 'height', 'auto', 2, 'active'),
        ('image', 'object-fit', 'contain', 3, 'active'),
        ('image', 'border-radius', '0', 4, 'active'),

        -- Table
        ('table', 'width', '100%', 1, 'active'),
        ('table', 'font-size', '14', 2, 'active'),
        ('table', 'color', '#000000', 3, 'active'),
        ('table', 'border', '1', 4, 'active'),
        ('table', 'border-style', 'solid', 5, 'active'),

        -- Divider
        ('divider', 'width', '100%', 1, 'active'),
        ('divider', 'height', '1', 2, 'active'),
        ('divider', 'background-color', '#000000', 3, 'active'),
        ('divider', 'margin', '0', 4, 'active'),

        -- Spacer
        ('spacer', 'height', '24', 1, 'active')
) AS seed_mappings (
    element_code,
    property_code,
    default_value,
    position,
    status
)
JOIN document_elements
    ON document_elements.code = seed_mappings.element_code
JOIN document_properties
    ON document_properties.code = seed_mappings.property_code
ON CONFLICT (document_element_id, document_property_id) DO NOTHING;
