CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS document_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Public identifier for frontend communication

    code TEXT NOT NULL,
    -- Example: text-align, font-size, margin

    name TEXT NOT NULL,
    -- Example: Text Alignment, Font Size, Margin Top

    data_type TEXT NOT NULL DEFAULT 'string',
    -- Values: string, number, boolean, json

    input_type TEXT NOT NULL DEFAULT 'text',
    -- Values: text, number, select, switch, color, textarea, grid-columns

    default_value TEXT NOT NULL DEFAULT '',
    -- Stored as text; application layer parses according to data_type

    unit TEXT NOT NULL DEFAULT '',
    -- Example: px, %, empty when not applicable

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_properties_data_type_chk
        CHECK (data_type IN ('string', 'number', 'boolean', 'json')),

    CONSTRAINT document_properties_input_type_chk
        CHECK (input_type IN ('text', 'number', 'select', 'switch', 'color', 'textarea', 'grid-columns')),

    CONSTRAINT document_properties_status_chk
        CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_properties_code_uq_idx
    ON document_properties (code);

CREATE UNIQUE INDEX IF NOT EXISTS document_properties_token_uq_idx
    ON document_properties (token);

CREATE INDEX IF NOT EXISTS document_properties_status_idx
    ON document_properties (status);

INSERT INTO document_properties (
    code,
    name,
    data_type,
    input_type,
    default_value,
    unit,
    status
) VALUES
    ('text-align', 'Text Align', 'string', 'select', 'left', '', 'active'),
    ('vertical-align', 'Vertical Align', 'string', 'select', 'top', '', 'active'),
    ('font-family', 'Font Family', 'string', 'select', 'Arial', '', 'active'),
    ('font-size', 'Font Size', 'number', 'number', '16', 'px', 'active'),
    ('margin', 'Margin', 'number', 'number', '24', 'px', 'active'),
    ('padding', 'Padding', 'number', 'number', '0', 'px', 'active'),
    ('border', 'Border', 'number', 'number', '1', 'px', 'active'),
    ('border-style', 'Border Style', 'string', 'select', 'solid', '', 'active'),
    ('gap', 'Gap', 'number', 'number', '0', 'px', 'active'),
    ('font-weight', 'Font Weight', 'string', 'select', '400', '', 'active'),
    ('font-style', 'Font Style', 'string', 'select', 'normal', '', 'active'),
    ('text-decoration', 'Text Decoration', 'string', 'select', 'none', '', 'active'),
    ('line-height', 'Line Height', 'number', 'number', '1.5', '', 'active'),
    ('color', 'Color', 'string', 'color', '#000000', '', 'active'),
    ('width', 'Width', 'string', 'text', 'auto', '', 'active'),
    ('height', 'Height', 'string', 'text', 'auto', '', 'active'),
    ('display', 'Display', 'string', 'select', 'block', '', 'active'),
    ('grid-template-columns', 'Grid Template Columns', 'json', 'grid-columns', '[100]', '%', 'active'),
    ('flex-direction', 'Flex Direction', 'string', 'select', 'row', '', 'active'),
    ('justify-content', 'Justify Content', 'string', 'select', 'flex-start', '', 'active'),
    ('align-items', 'Align Items', 'string', 'select', 'stretch', '', 'active'),
    ('list-style-type', 'List Style Type', 'string', 'select', 'disc', '', 'active'),
    ('border-radius', 'Border Radius', 'number', 'number', '0', 'px', 'active'),
    ('background-color', 'Background Color', 'string', 'color', '#FFFFFF', '', 'active'),
    ('background-image', 'Background Image', 'string', 'text', '', '', 'active')
ON CONFLICT (code) DO NOTHING;
