CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS document_property_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Public identifier for frontend communication

    document_property_id BIGINT NOT NULL REFERENCES document_properties (id) ON DELETE CASCADE,

    value TEXT NOT NULL,
    -- Example: left, center, right, top, Arial

    label TEXT NOT NULL,
    -- Example: Left, Center, Right, Top, Arial

    position INTEGER NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_property_options_status_chk
        CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_property_options_property_value_uq_idx
    ON document_property_options (document_property_id, value);

CREATE UNIQUE INDEX IF NOT EXISTS document_property_options_token_uq_idx
    ON document_property_options (token);

CREATE INDEX IF NOT EXISTS document_property_options_property_position_idx
    ON document_property_options (document_property_id, position);

CREATE INDEX IF NOT EXISTS document_property_options_status_idx
    ON document_property_options (status);

INSERT INTO document_property_options (
    document_property_id,
    value,
    label,
    position,
    status
) 
SELECT
    document_properties.id,
    seed_options.value,
    seed_options.label,
    seed_options.position,
    seed_options.status
FROM (
    VALUES
        -- Text align
        ('text-align', 'start', 'Start', 1, 'active'),
        ('text-align', 'left', 'Left', 2, 'active'),
        ('text-align', 'center', 'Center', 3, 'active'),
        ('text-align', 'right', 'Right', 4, 'active'),
        ('text-align', 'justify', 'Justify', 5, 'active'),

        -- Font family
        ('font-family', 'initial', 'Initial', 1, 'active'),
        ('font-family', 'Arial', 'Arial', 2, 'active'),
        ('font-family', 'Times New Roman', 'Times New Roman', 3, 'active'),
        ('font-family', 'Calibri', 'Calibri', 4, 'active'),

        -- Font weight
        ('font-weight', 'normal', 'Normal', 1, 'active'),
        ('font-weight', '400', 'Regular', 2, 'active'),
        ('font-weight', '500', 'Medium', 3, 'active'),
        ('font-weight', '600', 'Semi Bold', 4, 'active'),
        ('font-weight', '700', 'Bold', 5, 'active'),

        -- Font style
        ('font-style', 'normal', 'Normal', 1, 'active'),
        ('font-style', 'italic', 'Italic', 2, 'active'),

        -- Text decoration
        ('text-decoration', 'none', 'None', 1, 'active'),
        ('text-decoration', 'underline', 'Underline', 2, 'active'),
        ('text-decoration', 'line-through', 'Strike Through', 3, 'active'),

        -- Display
        ('display', 'inline', 'Inline', 1, 'active'),
        ('display', 'block', 'Block', 2, 'active'),
        ('display', 'grid', 'Grid', 3, 'active'),
        ('display', 'inline-block', 'Inline Block', 4, 'active'),
        ('display', 'none', 'None', 5, 'active'),

        -- Justify items
        ('justify-items', 'legacy', 'Legacy', 1, 'active'),
        ('justify-items', 'stretch', 'Stretch', 2, 'active'),
        ('justify-items', 'start', 'Start', 3, 'active'),
        ('justify-items', 'center', 'Center', 4, 'active'),
        ('justify-items', 'end', 'End', 5, 'active'),

        -- Align items
        ('align-items', 'normal', 'Normal', 1, 'active'),
        ('align-items', 'stretch', 'Stretch', 2, 'active'),
        ('align-items', 'flex-start', 'Flex Start', 3, 'active'),
        ('align-items', 'center', 'Center', 4, 'active'),
        ('align-items', 'flex-end', 'Flex End', 5, 'active'),
        ('align-items', 'baseline', 'Baseline', 6, 'active'),

        -- Color palette
        ('color', 'canvastext', 'Canvas Text', 1, 'active'),
        ('color', '#000000', 'Black', 2, 'active'),
        ('color', '#2563EB', 'Primary', 3, 'active'),
        ('color', '#64748B', 'Secondary', 4, 'active'),
        ('color', '#7C3AED', 'Accent', 5, 'active'),
        ('background-color', 'transparent', 'Transparent', 1, 'active'),
        ('background-color', '#FFFFFF', 'White', 2, 'active'),
        ('background-color', '#2563EB', 'Primary', 3, 'active'),
        ('background-color', '#64748B', 'Secondary', 4, 'active'),
        ('background-color', '#7C3AED', 'Accent', 5, 'active'),

        -- Size presets
        ('width', 'auto', 'Auto', 1, 'active'),
        ('width', '100%', 'Full', 2, 'active'),
        ('width', '50%', 'Half', 3, 'active'),
        ('width', 'custom', 'Custom', 4, 'active'),
        ('height', 'auto', 'Auto', 1, 'active'),
        ('height', '100%', 'Full', 2, 'active'),
        ('height', 'custom', 'Custom', 3, 'active'),
        ('opacity', '1', '100%', 1, 'active'),
        ('opacity', '0.5', '50%', 2, 'active'),
        ('opacity', '0.25', '25%', 3, 'active'),
        ('opacity', '0.1', '10%', 4, 'active'),
        ('opacity', 'custom', 'Custom', 5, 'active'),

        -- Object fit
        ('object-fit', 'fill', 'Fill', 1, 'active'),
        ('object-fit', 'contain', 'Contain', 2, 'active'),
        ('object-fit', 'cover', 'Cover', 3, 'active'),

        -- Spacing presets
        ('padding', '0', '0px', 1, 'active'),
        ('padding', '8', '8px', 2, 'active'),
        ('padding', '16', '16px', 3, 'active'),
        ('padding', '24', '24px', 4, 'active'),
        ('margin', '0', '0px', 1, 'active'),
        ('margin', '8', '8px', 2, 'active'),
        ('margin', '16', '16px', 3, 'active'),
        ('margin', '24', '24px', 4, 'active'),

        -- Border presets
        ('border', '0', 'None', 1, 'active'),
        ('border', '1', '1px', 2, 'active'),
        ('border', '2', '2px', 3, 'active'),
        ('border-style', 'none', 'None', 1, 'active'),
        ('border-style', 'solid', 'Solid', 2, 'active'),
        ('border-style', 'dashed', 'Dashed', 3, 'active'),
        ('border-style', 'dotted', 'Dotted', 4, 'active'),
        ('border-style', 'double', 'Double', 5, 'active'),
        ('border-radius', '0', 'None', 1, 'active'),
        ('border-radius', '4', '4px', 2, 'active'),
        ('border-radius', '8', '8px', 3, 'active'),
        ('border-radius', '16', '16px', 4, 'active'),

        -- Typography presets
        ('font-size', 'medium', 'Medium', 1, 'active'),
        ('font-size', '12', '12px', 2, 'active'),
        ('font-size', '14', '14px', 3, 'active'),
        ('font-size', '16', '16px', 4, 'active'),
        ('font-size', '20', '20px', 5, 'active'),
        ('font-size', '24', '24px', 6, 'active'),
        ('font-size', 'custom', 'Custom', 7, 'active'),
        ('line-height', 'normal', 'Normal', 1, 'active'),
        ('line-height', '1', 'Tight', 2, 'active'),
        ('line-height', '1.25', 'Compact', 3, 'active'),
        ('line-height', '1.5', 'Readable', 4, 'active'),
        ('line-height', '2', 'Relaxed', 5, 'active'),

        -- Grid template columns
        ('grid-template-columns', 'none', 'None', 1, 'active'),
        ('grid-template-columns', '[100]', 'Single', 2, 'active'),
        ('grid-template-columns', '[50,50]', 'Half', 3, 'active'),
        ('grid-template-columns', '[30,70]', 'Left', 4, 'active'),
        ('grid-template-columns', '[70,30]', 'Right', 5, 'active'),
        ('grid-template-columns', '[33,33,34]', 'Thirds', 6, 'active'),
        ('grid-template-columns', 'custom', 'Custom', 7, 'active')
) AS seed_options (
    property_code,
    value,
    label,
    position,
    status
)
JOIN document_properties
    ON document_properties.code = seed_options.property_code
ON CONFLICT (document_property_id, value) DO UPDATE
SET label = EXCLUDED.label,
    position = EXCLUDED.position,
    status = EXCLUDED.status,
    updated_at = NOW();
