CREATE TABLE IF NOT EXISTS document_element_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    document_element_id BIGINT NOT NULL REFERENCES document_elements (id) ON DELETE CASCADE,
    document_property_id BIGINT NOT NULL REFERENCES document_properties (id) ON DELETE CASCADE,

    default_value TEXT NOT NULL DEFAULT '',
    -- Example: 16, 24, #FFFFFF, flex-start

    position INTEGER NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'active',
    -- Values: active, inactive

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT document_element_properties_status_chk
        CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX IF NOT EXISTS document_element_properties_element_property_uq_idx
    ON document_element_properties (document_element_id, document_property_id);

CREATE INDEX IF NOT EXISTS document_element_properties_element_position_idx
    ON document_element_properties (document_element_id, position);

CREATE INDEX IF NOT EXISTS document_element_properties_property_idx
    ON document_element_properties (document_property_id);

CREATE INDEX IF NOT EXISTS document_element_properties_status_idx
    ON document_element_properties (status);

INSERT INTO document_element_properties (
    document_element_id,
    document_property_id,
    default_value,
    position,
    status
)
SELECT
    document_elements.id,
    document_properties.id,
    seed_mappings.default_value,
    seed_mappings.position,
    seed_mappings.status
FROM (
    VALUES
        -- Grid
        ('grid', 'display', 'grid', 1, 'active'),
        ('grid', 'grid-template-columns', '[100]', 2, 'active'),
        ('grid', 'width', 'auto', 3, 'active'),
        ('grid', 'height', 'auto', 4, 'active'),
        ('grid', 'gap', '0', 5, 'active'),
        ('grid', 'padding', '0', 6, 'active'),
        ('grid', 'margin', '0', 7, 'active'),
        ('grid', 'background-color', '#FFFFFF', 8, 'active'),
        ('grid', 'border', '0', 9, 'active'),
        ('grid', 'border-radius', '0', 10, 'active'),
        ('grid', 'justify-content', 'flex-start', 11, 'active'),
        ('grid', 'align-items', 'stretch', 12, 'active'),

        -- Text
        ('text', 'font-family', 'Arial', 1, 'active'),
        ('text', 'font-size', '16', 2, 'active'),
        ('text', 'font-weight', '400', 3, 'active'),
        ('text', 'line-height', '1.5', 4, 'active'),
        ('text', 'color', '#000000', 5, 'active'),
        ('text', 'text-align', 'left', 6, 'active'),
        ('text', 'margin', '0', 7, 'active'),

        -- Image
        ('image', 'width', 'auto', 1, 'active'),
        ('image', 'height', 'auto', 2, 'active'),
        ('image', 'margin', '0', 3, 'active'),
        ('image', 'border-radius', '0', 4, 'active'),
        ('image', 'background-image', '', 5, 'active'),

        -- List
        ('list', 'list-style-type', 'disc', 1, 'active'),
        ('list', 'font-family', 'Arial', 2, 'active'),
        ('list', 'font-size', '16', 3, 'active'),
        ('list', 'line-height', '1.5', 4, 'active'),
        ('list', 'color', '#000000', 5, 'active'),
        ('list', 'margin', '0', 6, 'active'),
        ('list', 'padding', '0', 7, 'active'),

        -- Table
        ('table', 'width', '100%', 1, 'active'),
        ('table', 'font-size', '14', 2, 'active'),
        ('table', 'color', '#000000', 3, 'active'),
        ('table', 'border', '1', 4, 'active'),
        ('table', 'border-radius', '0', 5, 'active'),

        -- Divider
        ('divider', 'width', '100%', 1, 'active'),
        ('divider', 'height', '1', 2, 'active'),
        ('divider', 'background-color', '#000000', 3, 'active'),
        ('divider', 'margin', '0', 4, 'active'),

        -- Spacer
        ('spacer', 'height', '24', 1, 'active'),

        -- Signature
        ('signature', 'width', '240', 1, 'active'),
        ('signature', 'height', '96', 2, 'active'),
        ('signature', 'margin', '0', 3, 'active'),
        ('signature', 'padding', '0', 4, 'active'),
        ('signature', 'border', '0', 5, 'active'),
        ('signature', 'border-radius', '0', 6, 'active'),
        ('signature', 'text-align', 'center', 7, 'active'),
        ('signature', 'font-family', 'Arial', 8, 'active'),
        ('signature', 'font-size', '14', 9, 'active'),
        ('signature', 'color', '#000000', 10, 'active'),

        -- QR Code
        ('qr-code', 'width', '120', 1, 'active'),
        ('qr-code', 'height', '120', 2, 'active'),
        ('qr-code', 'margin', '0', 3, 'active'),
        ('qr-code', 'padding', '0', 4, 'active'),
        ('qr-code', 'background-color', '#FFFFFF', 5, 'active'),

        -- Barcode
        ('barcode', 'width', '240', 1, 'active'),
        ('barcode', 'height', '80', 2, 'active'),
        ('barcode', 'margin', '0', 3, 'active'),
        ('barcode', 'background-color', '#FFFFFF', 4, 'active')
) AS seed_mappings (
    element_code,
    property_code,
    default_value,
    position,
    status
)
JOIN document_elements
    ON document_elements.code = seed_mappings.element_code
JOIN document_properties
    ON document_properties.code = seed_mappings.property_code
ON CONFLICT (document_element_id, document_property_id) DO NOTHING;
