CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Public identifier for frontend communication

    document_paper_id BIGINT NOT NULL REFERENCES document_papers (id),

    parent_id BIGINT REFERENCES documents (id) ON DELETE SET NULL,
    -- Nullable for original document. Used for cloned/versioned document lineage

    name TEXT NOT NULL,
    -- Example: Quotation Default, Invoice Default

    document_type TEXT NOT NULL DEFAULT 'custom',
    -- Example: quotation, purchase-order, invoice, service-report, custom

    position INTEGER NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'draft',
    -- Values: draft, active, inactive, archived, deleted

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT documents_status_chk
        CHECK (status IN ('draft', 'active', 'inactive', 'archived', 'deleted'))
);

CREATE UNIQUE INDEX IF NOT EXISTS documents_token_uq_idx
    ON documents (token);

CREATE INDEX IF NOT EXISTS documents_document_paper_id_idx
    ON documents (document_paper_id);

CREATE INDEX IF NOT EXISTS documents_parent_id_idx
    ON documents (parent_id);

CREATE INDEX IF NOT EXISTS documents_document_type_idx
    ON documents (document_type);

CREATE INDEX IF NOT EXISTS documents_position_idx
    ON documents (position);

CREATE INDEX IF NOT EXISTS documents_status_idx
    ON documents (status);

CREATE INDEX IF NOT EXISTS documents_created_at_idx
    ON documents (created_at DESC);
