CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active', -- Values: active, inactive, decline, completed

    project_value NUMERIC(18,2),
    -- Nilai proyek yang DISEPAKATI, dalam rupiah penuh. NULL berarti belum
    -- ditentukan, dan itu berbeda dari nol.
    --
    -- DICATAT, BUKAN DITURUNKAN, dan itu keputusan yang diambil sadar setelah
    -- sempat dirancang sebaliknya. Yang mengikat adalah angka pada PO pelanggan,
    -- sementara PO itu masuk sebagai LAMPIRAN — berkas pindaian tanpa satu pun
    -- angka yang dapat dibaca mesin. Penawaran kita punya grand_total, tetapi ia
    -- tawaran, bukan kesepakatan: ia sering direvisi di meja negosiasi, dan
    -- menjumlahkannya berarti melaporkan angka yang kita usulkan sebagai angka
    -- yang disetujui.
    --
    -- Menjumlahkan grand_total seluruh dokumen yang tertaut lewat
    -- project_documents juga SALAH, dan salahnya dua sampai tiga kali lipat:
    -- satu pekerjaan lazimnya punya penawaran, PO, dan faktur yang menyebut
    -- nilai yang sama. Ditambah dokumen ber-jenis purchase-order adalah kita
    -- MEMESAN KE PEMASOK — itu biaya, bukan pendapatan.
    --
    -- Kemudahan "langsung dari dokumen" tetap ada, tetapi di frontend sebagai
    -- USULAN: grand_total penawaran terakhir disodorkan sebagai nilai awal yang
    -- tinggal dikonfirmasi. Yang tersimpan di sini tetap angka yang benar-benar
    -- disetujui seseorang.
    --
    -- Kolom, BUKAN kantong JSONB seperti documents.variables. Kantong berguna
    -- ketika kuncinya berbeda-beda antar baris; di sini hanya ada satu angka,
    -- dan justru angka yang paling sering dilaporkan di seluruh sistem.
    -- Menaruhnya di kantong menukar penegakan tipe dan indeks biasa dengan
    -- pengecoran teks di setiap laporan — persis ongkos yang di documents
    -- terpaksa ditebus numericVariableKeys dan indeks ekspresi.

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Negatif ditolak; nol tidak. Proyek bernilai nol adalah keadaan yang sah —
    -- penggantian garansi, atau pekerjaan yang ditanggung sendiri. Yang memang
    -- belum ditentukan memakai NULL, dan itu perbedaan yang harus tetap terbaca.
    CONSTRAINT projects_value_non_negative_chk
        CHECK (project_value IS NULL OR project_value >= 0)
);

CREATE INDEX IF NOT EXISTS projects_status_idx ON projects (status);
CREATE INDEX IF NOT EXISTS projects_created_at_idx ON projects (created_at DESC);

-- Menyaring "proyek di atas sekian" dan mengurutkan menurut nilai. Baris yang
-- belum bernilai tidak ikut terindeks — ia memang tidak pernah dicari lewat
-- sini, dan mengeluarkannya membuat indeksnya hanya sebesar yang benar-benar
-- dipakai.
CREATE INDEX IF NOT EXISTS projects_value_idx
    ON projects (project_value)
    WHERE project_value IS NOT NULL;
