CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active', -- Values: active, inactive, decline, completed

    variables JSONB NOT NULL DEFAULT '{}',
    -- Kantong nilai tingkat proyek yang DIISI ORANG, bukan diturunkan dari
    -- dokumen. project_value tinggal di sini bersama yang lain.
    --
    -- Bentuknya mengikuti documents.variables persis: objek datar bernilai
    -- skalar, dengan penjaga yang sama di usecase. Dua kantong yang bentuknya
    -- berbeda akan menuntut dua penjaga, dua penjelasan, dan dua tempat yang
    -- suatu hari berselisih.
    --
    -- DIISI, BUKAN DITURUNKAN, dan itu bukan kemalasan. Nilai yang mengikat ada
    -- pada PO PELANGGAN, dan PO itu masuk sebagai lampiran — berkas pindaian
    -- tanpa satu pun angka yang dapat dibaca mesin. Penawaran kita punya
    -- grand_total, tetapi ia tawaran, bukan kesepakatan: ia direvisi di meja
    -- negosiasi, sehingga memakainya berarti melaporkan angka yang kita usulkan
    -- sebagai angka yang disetujui.
    --
    -- Menjumlahkan grand_total seluruh dokumen yang tertaut lewat
    -- project_documents pun salah berlipat: satu pekerjaan lazimnya punya
    -- penawaran, PO, dan faktur yang menyebut nilai yang sama. Ditambah dokumen
    -- ber-jenis purchase-order adalah KITA memesan ke pemasok — biaya, bukan
    -- pendapatan.
    --
    -- Kemudahan "langsung dari dokumen" tetap dapat diberikan, tetapi di
    -- frontend sebagai USULAN: grand_total penawaran terakhir disodorkan sebagai
    -- nilai awal yang tinggal dikonfirmasi atau dikoreksi. Yang tersimpan di
    -- sini tetap angka yang benar-benar disetujui seseorang.
    --
    -- JSONB sendiri tidak bertipe, tetapi INDEKS EKSPRESI di bawah ikut
    -- menegakkannya tanpa diminta: nilainya dihitung ketika barisnya DITULIS,
    -- sehingga "Rp 184.405.410" ditolak saat INSERT, bukan meledak saat laporan
    -- dibaca berbulan-bulan kemudian. Diperiksa langsung, bukan diduga.
    --
    -- Penjagaan itu tetap tidak cukup, dan penjaga di usecase tetap wajib —
    -- seperti numericVariableKeys pada dokumen. Dua sebabnya: galat dari indeks
    -- adalah galat Postgres mentah yang sampai ke klien sebagai 500 menyebut
    -- nama indeks, dan NEGATIF tetap lolos karena ia angka yang sah.
    --
    -- Ikutan yang harus diketahui: selama masih ada satu baris bernilai teks,
    -- indeks ini TIDAK DAPAT DIBUAT. Memasangnya belakangan pada data yang
    -- terlanjur kotor menuntut barisnya dibereskan lebih dulu.

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS projects_status_idx ON projects (status);
CREATE INDEX IF NOT EXISTS projects_created_at_idx ON projects (created_at DESC);

-- Indeks EKSPRESI atas project_value di dalam kantong.
--
-- Dengan kolom biasa indeks ini datang sendirinya. Dengan kantong ia harus
-- disebut, dan tanpanya setiap "proyek di atas sekian" dan setiap penjumlahan
-- memindai seluruh tabel sambil mengecor tiap barisnya.
CREATE INDEX IF NOT EXISTS projects_value_idx
    ON projects (((variables->>'project_value')::numeric));
