CREATE TABLE IF NOT EXISTS purchase_order_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order (id) ON DELETE CASCADE,
    asset_id BIGINT NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    category TEXT NOT NULL DEFAULT 'attachment', -- Example: attachment, signed, supporting_document
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS purchase_order_assets_purchase_order_id_asset_id_uq_idx
    ON purchase_order_assets (purchase_order_id, asset_id);

CREATE INDEX IF NOT EXISTS purchase_order_assets_purchase_order_id_idx
    ON purchase_order_assets (purchase_order_id);

CREATE INDEX IF NOT EXISTS purchase_order_assets_asset_id_idx
    ON purchase_order_assets (asset_id);
