CREATE TABLE IF NOT EXISTS purchase_order_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit TEXT NOT NULL DEFAULT '',
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    total DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS purchase_order_detail_purchase_order_id_idx
    ON purchase_order_detail (purchase_order_id);
