CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id BIGINT NOT NULL REFERENCES quotations (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS purchase_order_quotation_id_uq_idx ON purchase_order (quotation_id);
