CREATE TABLE IF NOT EXISTS quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_no TEXT NOT NULL,
    client_name TEXT NOT NULL,
    attn_name TEXT NOT NULL DEFAULT '',
    attn_position TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    project TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new',
    discount_type TEXT NOT NULL DEFAULT '',
    discount_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS quotations_quotation_no_uq_idx ON quotations (quotation_no);
CREATE INDEX IF NOT EXISTS quotations_created_at_idx ON quotations (created_at DESC);
CREATE INDEX IF NOT EXISTS quotations_status_idx ON quotations (status);

CREATE OR REPLACE FUNCTION generate_quotation_no()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    current_year TEXT := TO_CHAR(CURRENT_DATE, 'YYYY');
    next_number INTEGER;
BEGIN
    SELECT
        COALESCE(
            MAX(
                (
                    regexp_match(
                        quotation_no,
                        '^Q-' || current_year || '-([0-9]{4})$'
                    )
                )[1]::INTEGER
            ),
            0
        ) + 1
    INTO next_number
    FROM quotations
    WHERE quotation_no LIKE 'Q-' || current_year || '-%';

    RETURN 'Q-' || current_year || '-' || LPAD(next_number::TEXT, 4, '0');
END;
$$;
