CREATE TABLE IF NOT EXISTS quotation_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES quotation_sections (id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS quotation_details_section_id_position_idx
    ON quotation_details (section_id, position);
