CREATE TABLE IF NOT EXISTS quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES quotation_sections (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit TEXT NOT NULL DEFAULT '',
    price DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS quotation_items_section_id_idx ON quotation_items (section_id);
