CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_uq_idx ON users (email);

-- Cap waktu dijaga TRIGGER, bukan oleh aplikasi.
--
-- Tidak ada satu pun jalur di aplikasi yang menulis ke tabel ini — user dibuat
-- dan diubah manual lewat SQL. Kalau updated_at diserahkan ke pemanggil, ia
-- hanya akan benar pada baris yang kebetulan diubah oleh orang yang ingat
-- menyertakannya, dan kolom yang benar sebagian lebih menyesatkan daripada
-- kolom yang tidak ada.
--
-- Fungsinya diulang di sini, bukan diambil dari assets.sql yang juga
-- mendefinisikannya. Berkas migration di repo ini dijalankan manual satu per
-- satu, dan users.sql dijalankan LEBIH DULU menurut urutan baseline — berkas
-- yang hanya berhasil bila berkas lain sudah dijalankan adalah jebakan.
-- CREATE OR REPLACE membuat pengulangannya tidak berakibat apa pun.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_set_updated_at_trg ON users;

CREATE TRIGGER users_set_updated_at_trg
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Benih akun. Dijalankan berulang tanpa akibat.
--
-- Sandinya TIDAK ditulis di sini, bahkan sebagai komentar. Berkas ini masuk
-- git, dan sandi yang pernah masuk git tetap ada di riwayat walau barisnya
-- dihapus kemudian — menghapusnya menuntut menulis ulang sejarah yang sudah
-- terbit. Yang tersimpan hash bcrypt, dan itu memang gunanya: ia aman dibaca
-- siapa pun yang membaca repo ini.
--
-- ON CONFLICT DO NOTHING, bukan DO UPDATE. Menjalankan ulang berkas ini tidak
-- boleh mengembalikan sandi yang sudah diganti orangnya — benih adalah keadaan
-- AWAL, bukan keadaan yang dipaksakan terus-menerus.
--
-- role disebut eksplisit ketiganya, tidak menumpang bawaan kolom. Bawaannya
-- 'user', nilai yang tidak dikenal kode mana pun dan tidak dimiliki satu baris
-- pun — baris yang menumpang bawaan itu akan lahir tanpa wewenang apa pun, dan
-- gejalanya muncul jauh kemudian sebagai 403 yang tidak menyebut sebabnya.
INSERT INTO users (name, email, password, role) VALUES
    ('Fahmi',  'fahmi@widiakencana.com',  '$2a$10$bxFPoKvi7UtgW.7p0/c5YeIrPE/mr2NiZR1YTDg2jjyo87i4n3HCS', 'superadmin'),
    ('Fakhri', 'fakhri@widiakencana.com', '$2a$10$6UpRAZrSYS0yDvqh.FUg7.5n.OL3CfrngSusdz5UCMcF7kQ6rm7IG', 'superadmin'),
    -- Agent memakai baris users seperti manusia, dan itu yang membuat presence,
    -- kursor, dan tiket bekerja untuknya tanpa jalur kedua. Yang membedakan
    -- hanya perannya, dan peran itulah yang menutup rute di luar penyuntingan.
    ('AI Agent', 'ai-agent@widiakencana.com', '$2a$10$Vv.XLetA5HC8Y3jn5DmrmuaBOtUI/uvk8.lnits3lQJuFGlo7api2', 'ai-agent')
ON CONFLICT (email) DO NOTHING;
