CREATE TABLE IF NOT EXISTS workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- Example: Standard Project Flow
    status TEXT NOT NULL DEFAULT 'active', -- Values: active, inactive, deleted
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS workflows_name_uq_idx ON workflows (name);
CREATE INDEX IF NOT EXISTS workflows_status_idx ON workflows (status);
CREATE INDEX IF NOT EXISTS workflows_created_at_idx ON workflows (created_at DESC);
