CREATE TABLE IF NOT EXISTS workflow_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL REFERENCES workflows (id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- Example: Sales, Delivery, Finance, Closing
    position INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active', -- Values: active, inactive, deleted
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS workflow_stages_workflow_id_name_uq_idx
    ON workflow_stages (workflow_id, name);

CREATE INDEX IF NOT EXISTS workflow_stages_workflow_id_position_idx
    ON workflow_stages (workflow_id, position);

CREATE INDEX IF NOT EXISTS workflow_stages_status_idx ON workflow_stages (status);
