CREATE TABLE IF NOT EXISTS workflow_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_stage_id BIGINT NOT NULL REFERENCES workflow_stages (id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- Example: Quotation, Purchase Order, Kick Off, Installation, Invoice, Payment
    position INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active', -- Values: active, inactive, deleted
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS workflow_steps_workflow_stage_id_name_uq_idx
    ON workflow_steps (workflow_stage_id, name);

CREATE INDEX IF NOT EXISTS workflow_steps_workflow_stage_id_position_idx
    ON workflow_steps (workflow_stage_id, position);

CREATE INDEX IF NOT EXISTS workflow_steps_status_idx ON workflow_steps (status);
